### ISSUE TITLE
Invalid signature error

### ISSUE THREAD

**Issue by leiluspocus** [ooyala/nodejs-ooyala-v2-sdk#2]
Hi Ooyala !

First of all, thank you for this amazing app. 

I tried it on my end and I wanted to let you know that there were a little bug in the generateSignature function in the line 185 of the lib/Ooyala.js file. 

I had an error saying "Invalid signature" for the following API query : /v2/assets?where=metadata.my_meta_data='myvalue' 

I replaced 
`stringToSign += (requestBody) ? requestBody : '';`
with 
`stringToSign += (requestBody != "null") ? requestBody : '';`

In order to avoid to encrypt a body if we're not sending any. 

Let me know if you need more information :)

Keep up the great work ! :clap:

**Comment by fortino-ooyala** [comment]
thanks for the issue, I just push a new release with the changes https://github.com/ooyala/nodejs-ooyala-v2-sdk/releases/tag/0.0.7 let me know if something is not working.
